default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  # /etc/hosts
  # 127.0.0.1 postgres
  host: postgres
  database: campo_development
  username: wutong

test:
  <<: *default
  host: postgres
  database: campo_test
  username: postgres

production:
  <<: *default
  # DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
  url: <%= ENV["DATABASE_URL"] %>
