default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>

development:
  <<: *default
  database: musicapp_development

test:
  <<: *default
  database: musicapp_test

production:
  <<: *default
  database: musicapp_production
  password: <%= ENV['DB_PASSWORD'] %>
